backend:
  name: git-gateway
  branch: main

media_folder: "img/productos"
public_folder: "/img/productos"

collections:
  - name: "configuracion" # Puedes darle el nombre que quieras a la colección
    label: "Configuración de Productos"
    files: # Usamos 'files' en lugar de 'folder' para un archivo único
      - label: "Lista de Productos"
        name: "productos"
        file: "js/productos.json"
        fields:
          - label: "Productos"
            name: "lista_productos"
            widget: "list"
            fields:
              - {label: "ID", name: "id", widget: "number"}
              - {label: "Nombre", name: "nombre", widget: "string"}
              - {label: "Precio", name: "precio", widget: "number"}
              - {label: "Categoría", name: "categoria", widget: "select", options: ["Ropa", "Calzado", "Tecnología", "Hogar"]}
              - {label: "Descripción", name: "descripcion", widget: "text"}
              - label: "Imágenes"
                name: "imagenes"
                widget: "list"
                summary: "{{fields.url}}"
                fields:
                  - {label: "Imagen", name: "url", widget: "image"}